import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { homePath, ticketsPath } from "./paths";

const InterSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterSans.variable} antialiased`}>
        <nav
          className="
        supports-backdrop-blur:bg-background/60 fixed left-0 right-0 top-0 z-20 border-b bg-background/95 backdrop-blur w-full flex py-2.5 px-5 justify-between
        "
        >
          <div className="">
            <Link href={homePath()}>Home</Link>
          </div>
          <div className="">
            <Link href={ticketsPath()}>Tickets</Link>
          </div>
        </nav>
        <main
          className="
          min-h-screen flex-1 overflow-y-auto overflow-x-hidden py-24 px-8 bg-secondary/20 flex flex-col
        "
        >
          {children}
        </main>
      </body>
    </html>
  );
}
